name: 'TAMULib Coveralls for Java'
description: 'Run Tests and send results to coveralls.'

inputs:
  coveralls_repo_token:
    description: 'Coveralls token for the repository'
    required: true
  coveralls_build_number:
    description: 'Build Number or identifier for this coveralls build'
    required: true
  coveralls_parallel:
    description: 'Set to parallel coveralls build'
    required: false
    default: false

runs:
  using: "composite"

  steps:

  # Run Tests.
  - name: Running Tests for Java
    env:
      COVERALLS_BUILD_NUMBER: ${{ inputs.coveralls_build_number }}
      COVERALLS_REPO_TOKEN: ${{ inputs.coveralls_repo_token }}
      COVERALLS_PARALLEL: ${{ inputs.coveralls_parallel }}
    run: |
      mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      mvn clean test cobertura:cobertura jacoco:report coveralls:report -DserviceName="github-actions" -DserviceBuildNumber="$COVERALLS_BUILD_NUMBER"
